### ISSUE TITLE
What is the protocol for getting audio?

### ISSUE THREAD

**Issue by hemisemidemipresent** [Jasonnor/th-music-video-generator#25]
i.e. what is the best practice (if any) for getting the audio from the newer games?

**Comment by Jasonnor** [comment]
I usually get it from some unofficial Touhou Wiki, or convert it from my game audio source.

I will upload these music when I have time 😄 : 鬼形獣、虹龍洞、秘封噩夢日記 and 剛欲異聞.

**Comment by hemisemidemipresent** [comment]
sure

**Comment by hemisemidemipresent** [comment]
are there accommodation for music cds?
