### ISSUE TITLE
Music song numbers off

### ISSUE THREAD

**Issue by hemisemidemipresent** [Jasonnor/th-music-video-generator#28]
see [this comment](https://github.com/Jasonnor/th-music-video-generator/issues/13#issuecomment-1008024104) on how this will make #13 easier to implement

edit: list:

-    [x] th01
-    [x] th02
-    [x] th03
-    [x] th04
-    [x] th05
-    [x] th06
-    [x] th07
-    [ ] th07.5
-    [x] th08
-    [x] th09
-    [x] th09.5
-    [x] th10
-    [ ] th10.5
-    [x] th11
-    [x] th12
-    [ ] th12.3
-    [x] th12.5
-    [ ] th12.8
-    [x] th13
-    [ ] th13.5
-    [x] th14
-    [x] th14.3
-    [ ] th14.5
-    [x] th15
-    [ ] th15.5
-    [x] th16

**Comment by Jasonnor** [comment]
Got it! I will merge th04.

Currently I maintain Firebase manually as updates are infrequent and will continue to do so in the future.

**Comment by Jasonnor** [comment]
Will work after GitHub page build done :)

https://github.com/Jasonnor/th-music-video-generator/actions/runs/1703197517

**Comment by hemisemidemipresent** [comment]
There are still many decimals games that have song numbers off

**Comment by hemisemidemipresent** [comment]
@Jasonnor can you reopen this issue?

**Comment by Jasonnor** [comment]
Sure!

**Comment by Jasonnor** [comment]
Will work after GitHub page build done!
https://github.com/Jasonnor/th-music-video-generator/actions/runs/1732182335
