### ISSUE TITLE
Feature: Add new music and image of new Touhou series

### ISSUE THREAD

**Issue by Jasonnor** [Jasonnor/th-music-video-generator#35]
- [X] 秘封ナイトメアダイアリー
- [X] 東方鬼形獣
- [x] 東方剛欲異聞
- [x] 東方虹龍洞

_Originally posted by @Jasonnor in https://github.com/Jasonnor/th-music-video-generator/issues/25#issuecomment-1003255022_

**Comment by hemisemidemipresent** [comment]
I suppose also add the missing music?

**Comment by Jasonnor** [comment]
Sure! Would be later. Some of the music is missing because there are too many tracks in the .5 series, so I didn't put them all at that time. (Simply put, lazy 😅)

**Comment by Jasonnor** [comment]
東方鬼形獣 Done!

**Comment by Jasonnor** [comment]
秘封ナイトメアダイアリー Done!

**Comment by Jasonnor** [comment]
![image](https://user-images.githubusercontent.com/7609173/168486692-d07da66b-53ab-4e98-b76a-2a722eb25b4a.png)

🤩

**Comment by latious** [comment]
Thank you so much! Really appreciate your work.
Especially for the new Touhou game music.

**Comment by hemisemidemipresent** [comment]
Nice, by the way where are the youtube videos stored? There doesnt seem to be any valid videos for the newer games

**Comment by Jasonnor** [comment]
@hemisemidemipresent 

These video data are placed in `database/th-song.json`, I will manually update to Firebase!

Currently YouTube videos are obtained in two ways:

1. The specified `video_id` and optional start time `time`

e.g.,
![image](https://user-images.githubusercontent.com/7609173/169046691-341882ab-a652-4a6b-9631-574e1fb1a13c.png)

2. The first video searched from YouTube based on `keyword`

e.g.,
![image](https://user-images.githubusercontent.com/7609173/169046711-58fbe63a-a964-41d4-ae85-70eb651efe96.png)

Yesterday I updated the YouTube videos of 東方鬼形獣 and 東方剛欲異聞.

The rest of the videos will be added soon! 😄
